DROP TABLE IF EXISTS card_likes CASCADE;

CREATE TABLE card_likes (
  id SERIAL PRIMARY KEY NOT NULL,
   user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
   card_id INTEGER REFERENCES cards(id) ON DELETE CASCADE
);
